export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import "./globals.css";
import { UserProvider } from "./UserContext/UserContextProvider";
 
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="h-full">
      <head>
      <meta charSet="UTF-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <title>RoomieManager</title>

      <link rel="preconnect" href="https://fonts.googleapis.com"/>
      <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous"/>
      <link href="https://fonts.googleapis.com/css2?family=ABeeZee:ital@0;1&family=Acme&family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=Josefin+Sans:wght@300&family=Julee&family=Pangolin&display=swap" rel="stylesheet"/>
      </head>

      <body className="h-full"><UserProvider>{children}</UserProvider></body>
        
    </html>
  );
}

